addons:
  sonarcloud:
    organization: "anteatergames" # the key of the org you chose at step #3
    token:
      secure: "db9ce9d761b422069fc1c2cb0d82d928054bd218" # encrypted value of your token

script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  
jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.sonar/cache'